import { useState } from "react";
import { fetchJSON, idempotentHeaders } from "../lib/api";
import { AsyncState } from "../components/OperationalUI";

const input = "w-full rounded-xl border p-3";
function Tool({ title, description, children }) { return <section className="panel-card"><h3 className="font-semibold">{title}</h3><p className="mt-1 text-sm text-primary/55">{description}</p><div className="mt-4">{children}</div></section>; }
export default function AdminTools() {
  const [workflow, setWorkflow] = useState(""), [diagnostic, setDiagnostic] = useState(null), [order, setOrder] = useState(""), [estimatedDelivery, setEstimatedDelivery] = useState(""), [action, setAction] = useState(""), [user, setUser] = useState(""), [customer, setCustomer] = useState(""), [activationCode, setActivationCode] = useState(""), [reason, setReason] = useState(""), [message, setMessage] = useState(""), [error, setError] = useState(""), [pending, setPending] = useState(false);
  const run = async (path, body = {}) => { if (!reason.trim()) { setError("ثبت دلیل اصلاح الزامی است."); return; } setPending(true); setError(""); try { const response = await fetchJSON(path, { method: "POST", headers: idempotentHeaders(), body: JSON.stringify({ ...body, reason }) }); setMessage("عملیات با Audit کامل انجام شد."); return response.data; } catch (e) { setError(`${e.message}${e.requestId ? ` — کد پیگیری: ${e.requestId}` : ""}`); } finally { setPending(false); } };
  const diagnose = async () => { setPending(true); setError(""); try { const response = await fetchJSON(`/api/v1/admin/diagnostics/workflows/${workflow}`); setDiagnostic(response.data); } catch (e) { setError(e.message); } finally { setPending(false); } };
  return <div className="space-y-5" dir="rtl"><header className="panel-card"><h2 className="font-display text-2xl">ابزارهای اصلاح امن</h2><p className="mt-2 text-sm text-primary/60">این ابزارها SQL اجرا نمی‌کنند و فقط عملیات شناخته‌شده، محدود و Auditشده را انجام می‌دهند.</p></header>{error && <AsyncState error={error} />}{message && <p className="rounded-xl bg-green-50 p-4 text-sm text-green-800" role="status">{message}</p>}
    <label className="panel-card block text-sm font-medium">دلیل مشترک عملیات اصلاحی<textarea value={reason} onChange={(e) => setReason(e.target.value)} className={`${input} mt-2 min-h-24`} /></label>
    <div className="grid gap-5 lg:grid-cols-2"><Tool title="عیب‌یابی Workflow" description="مرحله جاری، Action Item و ناسازگاری اجرای Workflow را بررسی می‌کند."><div className="flex gap-2"><input value={workflow} onChange={(e) => setWorkflow(e.target.value)} className={input} placeholder="Workflow Instance ID"/><button disabled={pending || !workflow} onClick={diagnose} className="rounded-xl bg-primary px-5 text-sand disabled:opacity-40">بررسی</button></div>{diagnostic && <div className="mt-4 space-y-2">{diagnostic.findings?.length ? diagnostic.findings.map((item) => <div key={item.code} className="rounded-xl bg-amber-50 p-3 text-sm"><b>{item.code}</b>{item.safe_repair && <button disabled={pending} onClick={() => run(`/api/v1/admin/diagnostics/workflows/${workflow}/repair`, { repair_code: item.code === "CURRENT_STEP_MISSING" ? "SET_SINGLE_CURRENT_STEP" : "REBUILD_CURRENT_ACTION" })} className="mr-3 underline">Repair امن</button>}</div>) : <p className="rounded-xl bg-green-50 p-3 text-sm">ناسازگاری شناخته‌شده‌ای پیدا نشد.</p>}</div>}</Tool>
      <Tool title="اصلاح سفارش" description="Progress، مانده مالی یا ETA سفارش را از ابزارهای محدود اصلاح می‌کند."><input value={order} onChange={(e) => setOrder(e.target.value)} className={input} placeholder="Order ID"/><input aria-label="زمان تحویل تخمینی" type="datetime-local" value={estimatedDelivery} onChange={(e) => setEstimatedDelivery(e.target.value)} className={`${input} mt-2`}/><div className="mt-3 flex flex-wrap gap-2"><button disabled={pending || !order} onClick={() => run(`/api/v1/admin/tools/orders/${order}/recalculate-progress`)} className="rounded-full border px-4 py-2">محاسبه پیشرفت</button><button disabled={pending || !order} onClick={() => run(`/api/v1/admin/tools/orders/${order}/reconcile-payment`)} className="rounded-full border px-4 py-2">تطبیق مانده پرداخت</button><button disabled={pending || !order || !estimatedDelivery} onClick={() => run(`/api/v1/admin/tools/orders/${order}/estimated-delivery`, {estimated_delivery_at:new Date(estimatedDelivery).toISOString()})} className="rounded-full border px-4 py-2">اصلاح ETA</button></div></Tool>
      <Tool title="بستن Action Item گیرکرده" description="اقدام باز اشتباه را بدون حذف رکورد تکمیل می‌کند."><input value={action} onChange={(e) => setAction(e.target.value)} className={input} placeholder="Action Item ID"/><button disabled={pending || !action} onClick={() => run(`/api/v1/admin/tools/action-items/${action}/resolve`)} className="mt-3 rounded-full border px-4 py-2">Resolve با دلیل</button></Tool>
      <Tool title="خروج اجباری کاربر" description="Refresh Tokenها و Access Tokenهای صادرشده قبلی را باطل می‌کند."><input value={user} onChange={(e) => setUser(e.target.value)} className={input} placeholder="User ID"/><button disabled={pending || !user} onClick={() => run(`/api/v1/admin/users/${user}/revoke-sessions`)} className="mt-3 rounded-full border border-red-300 px-4 py-2 text-red-700">ابطال Sessionها</button></Tool>
      <Tool title="صدور مجدد کد فعال‌سازی" description="کد قبلی باطل می‌شود و کد تازه فقط پس از پاسخ موفق نمایش داده می‌شود."><input value={customer} onChange={(e) => { setCustomer(e.target.value); setActivationCode(""); }} className={input} placeholder="Customer User ID"/><button disabled={pending || !customer} onClick={async () => { const result=await run(`/api/v1/admin/customers/${customer}/regenerate-activation`);if(result?.activation_code)setActivationCode(result.activation_code); }} className="mt-3 rounded-full border px-4 py-2">ساخت کد جدید</button>{activationCode&&<p className="mt-3 rounded-xl bg-amber-50 p-3 text-center font-mono text-lg" role="status">{activationCode}</p>}</Tool>
    </div></div>;
}
