import { useEffect, useState } from "react";
import { fetchJSON } from "../lib/api";
import { AsyncState, FilterBar, ListPage, Pagination, PersianDate } from "../components/OperationalUI";

const initial = { search: "", actor: "", entity: "", action: "", order: "", from: "", to: "" };
export default function Audit() {
  const [filters, setFilters] = useState(initial), [page, setPage] = useState(1), [data, setData] = useState({ items: [], total: 0, pageSize: 25 }), [loading, setLoading] = useState(true), [error, setError] = useState(""), [advanced, setAdvanced] = useState(null);
  const load = () => { setLoading(true); setError(""); const params = new URLSearchParams({ ...filters, page: String(page), pageSize: "25" }); fetchJSON(`/api/v1/admin/audit?${params}`).then((response) => setData(response.data || { items: [], total: 0, pageSize: 25 })).catch((e) => setError(e.message)).finally(() => setLoading(false)); };
  useEffect(() => { const timer = setTimeout(load, 250); return () => clearTimeout(timer); }, [filters, page]);
  const change = (key, value) => { setFilters((current) => ({ ...current, [key]: value })); setPage(1); };
  const filtersView = <FilterBar onClear={() => { setFilters(initial); setPage(1); }}><input aria-label="جست‌وجوی عملیات یا موجودیت" className="rounded-xl border p-3" placeholder="جست‌وجوی عملیات یا موجودیت" value={filters.search} onChange={(e) => change("search", e.target.value)} /><input aria-label="شناسه کاربر" className="rounded-xl border p-3" placeholder="Actor User ID" value={filters.actor} onChange={(e) => change("actor", e.target.value)} /><input aria-label="نوع موجودیت" className="rounded-xl border p-3" placeholder="نوع موجودیت" value={filters.entity} onChange={(e) => change("entity", e.target.value)} /><input aria-label="شناسه سفارش" className="rounded-xl border p-3" placeholder="Order ID" value={filters.order} onChange={(e) => change("order", e.target.value)} /><label className="text-xs">از تاریخ<input type="date" className="mt-1 block w-full rounded-xl border p-3" value={filters.from} onChange={(e) => change("from", e.target.value)} /></label><label className="text-xs">تا تاریخ<input type="date" className="mt-1 block w-full rounded-xl border p-3" value={filters.to} onChange={(e) => change("to", e.target.value)} /></label></FilterBar>;
  return <ListPage title="گزارش تغییرات" description="چه کسی، چه زمانی و با چه دلیلی داده عملیاتی را تغییر داده است." filters={filtersView}>
    <AsyncState loading={loading} error={error} empty={!data.items?.length} emptyText="رویدادی مطابق فیلترها پیدا نشد." retry={load}><section className="panel-card overflow-x-auto"><table className="w-full min-w-[800px] text-right text-sm"><thead><tr><th className="p-2">کاربر</th><th>عملیات</th><th>موجودیت</th><th>زمان</th><th>Reason / خلاصه</th><th>جزئیات</th></tr></thead><tbody>{data.items?.map((item) => <tr className="border-t align-top" key={item.id}><td className="p-2">{item.actor}</td><td><code>{item.action}</code></td><td>{item.entity}<small className="block text-primary/45">{item.entity_id}</small></td><td><PersianDate value={item.created_at} /></td><td className="max-w-xs"><span className="line-clamp-2">{item.after?.reason || item.metadata?.reason || "—"}</span></td><td><button type="button" onClick={() => setAdvanced(item)} className="rounded-full border px-3 py-1">Advanced</button></td></tr>)}</tbody></table><Pagination page={page} pageSize={data.pageSize || 25} total={data.total || 0} onChange={setPage} /></section></AsyncState>
    {advanced && <div className="fixed inset-0 z-50 flex items-center justify-center bg-black/40 p-4" onMouseDown={(e) => e.target === e.currentTarget && setAdvanced(null)}><section role="dialog" aria-modal="true" className="max-h-[80vh] w-full max-w-3xl overflow-auto rounded-3xl bg-white p-6"><div className="flex justify-between"><h3 className="font-semibold">جزئیات Audit #{advanced.id}</h3><button type="button" onClick={() => setAdvanced(null)} aria-label="بستن">×</button></div><pre dir="ltr" className="mt-4 overflow-auto rounded-xl bg-slate-950 p-4 text-xs text-slate-100">{JSON.stringify({ before: advanced.before, after: advanced.after, metadata: advanced.metadata, requestId: advanced.request_id }, null, 2)}</pre></section></div>}
  </ListPage>;
}
