import { useEffect, useMemo, useState } from "react";
import { Link, useParams } from "react-router-dom";
import { fetchJSON } from "../lib/api";
import { useAuth } from "../lib/auth";

const fa = {DRAFT:"پیش‌نویس",PLANNED:"برنامه‌ریزی‌شده",IN_PRODUCTION:"در تولید",PACKAGED:"بسته‌بندی‌شده",READY_FOR_SHIPMENT:"آماده ارسال",LOADING:"در حال بارگیری",LOADED:"بارگیری‌شده",IN_TRANSIT:"در مسیر",ARRIVED:"رسیده",PARTIALLY_DELIVERED:"تحویل جزئی",DELIVERED:"تحویل‌شده",CANCELLED:"لغوشده"};
const Badge=({children})=><span className="rounded-full bg-primary/10 px-3 py-1 text-xs">{fa[children]||children}</span>;
const Empty=()=> <p className="py-10 text-center text-sm text-primary/50">موردی ثبت نشده است.</p>;
const ErrorBox=({value})=>value?<p className="rounded-xl bg-red-50 p-4 text-red-700">{value}</p>:null;

export function Batches(){
  const [items,setItems]=useState([]),[status,setStatus]=useState(""),[error,setError]=useState("");
  useEffect(()=>{fetchJSON(`/api/v1/batches${status?`?status=${status}`:""}`).then(r=>setItems(r.data||[])).catch(e=>setError(e.message))},[status]);
  return <div className="space-y-5" dir="rtl"><section className="panel-card flex flex-wrap items-center justify-between gap-3"><div><h2 className="font-display text-2xl">بچ‌های اجرایی</h2><p className="text-sm text-primary/60">تقسیم، ادغام، منبع و پیشرفت هر بخش سفارش</p></div><select className="rounded-full border px-4 py-2" value={status} onChange={e=>setStatus(e.target.value)}><option value="">همه وضعیت‌ها</option>{Object.keys(fa).map(x=><option key={x}>{x}</option>)}</select></section><ErrorBox value={error}/><section className="panel-card overflow-x-auto">{!items.length?<Empty/>:<table className="w-full text-sm"><thead><tr className="border-b text-right"><th className="p-3">شماره</th><th>سفارش</th><th>سنگ</th><th>مقدار</th><th>وضعیت</th></tr></thead><tbody>{items.map(x=><tr key={x.id} className="border-b"><td className="p-3"><Link className="font-semibold underline" to={`/dashboard/batches/${x.id}`}>{x.batch_number}</Link></td><td>{x.order_number}</td><td>{x.stone_name}</td><td dir="ltr">{x.actual_quantity} / {x.planned_quantity} {x.quantity_unit}</td><td><Badge>{x.status}</Badge></td></tr>)}</tbody></table>}</section></div>;
}

export function BatchDetail(){
  const {id}=useParams(),{hasPermission}=useAuth();
  const [batch,setBatch]=useState(null),[reservations,setReservations]=useState([]),[error,setError]=useState("");
  const load=()=>Promise.all([fetchJSON(`/api/v1/batches/${id}`),hasPermission("inventory.reservations.view")?fetchJSON(`/api/v1/batches/${id}/reservations`):Promise.resolve({data:[]})]).then(([b,r])=>{setBatch(b.data);setReservations(r.data||[])}).catch(e=>setError(e.message));
  useEffect(()=>{load()},[id]);
  const cancel=async()=>{const reason=prompt("دلیل لغو بچ:");if(!reason)return;await fetchJSON(`/api/v1/batches/${id}/cancel`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({reason})});load()};
  if(!batch)return <div className="panel-card">{error||"در حال بارگذاری…"}</div>;
  return <div className="space-y-5" dir="rtl"><section className="panel-card"><Link to="/dashboard/batches" className="text-sm underline">بازگشت</Link><div className="mt-3 flex flex-wrap justify-between gap-3"><div><h2 className="font-display text-2xl">{batch.batch_number}</h2><p>{batch.stone_name} • سفارش {batch.order_number}</p></div><Badge>{batch.status}</Badge></div><div className="mt-5 grid gap-3 sm:grid-cols-3"><div className="rounded-xl bg-primary/5 p-4">برنامه: <b dir="ltr">{batch.planned_quantity} {batch.quantity_unit}</b></div><div className="rounded-xl bg-primary/5 p-4">واقعی: <b dir="ltr">{batch.actual_quantity} {batch.quantity_unit}</b></div><div className="rounded-xl bg-primary/5 p-4">منبع: <b>{batch.source_type}</b></div></div>{batch.workflow_instance_id&&<Link className="mt-4 inline-block rounded-full bg-primary px-5 py-2 text-sand" to={`/dashboard/workflows/${batch.workflow_instance_id}`}>باز کردن Workflow</Link>}{hasPermission("batches.cancel")&&!['CANCELLED','SPLIT','MERGED','DELIVERED'].includes(batch.status)&&<button onClick={cancel} className="mr-2 rounded-full border border-red-300 px-5 py-2 text-red-700">لغو</button>}</section><section className="panel-card"><h3 className="font-semibold">رزروهای موجودی</h3>{!reservations.length?<Empty/>:reservations.map(x=><div key={x.id} className="mt-3 flex justify-between rounded-xl border p-3"><span>{x.inventory_lot_id}</span><span dir="ltr">{x.reserved_quantity} {x.quantity_unit}</span><Badge>{x.status}</Badge></div>)}</section><ErrorBox value={error}/></div>;
}

export function Inventory(){
 const {hasPermission}=useAuth();const [lots,setLots]=useState([]),[locations,setLocations]=useState([]),[summary,setSummary]=useState({}),[location,setLocation]=useState(""),[selected,setSelected]=useState(null),[trace,setTrace]=useState([]),[error,setError]=useState("");
 const load=()=>Promise.all([fetchJSON(`/api/v1/inventory/lots${location?`?location_id=${location}`:""}`),fetchJSON('/api/v1/inventory/locations'),fetchJSON('/api/v1/inventory/summary')]).then(([l,loc,s])=>{setLots(l.data||[]);setLocations(loc.data||[]);setSummary(s.data||{})}).catch(e=>setError(e.message));useEffect(()=>{load()},[location]);
 const showTrace=async lot=>{setSelected(lot);const r=await fetchJSON(`/api/v1/inventory/lots/${lot.id}/traceability`);setTrace(r.data||[])};
 return <div className="space-y-5" dir="rtl"><section className="grid gap-3 sm:grid-cols-3">{[["Lot فعال",summary.active_lots],["موجودی کم",summary.low_stock],["رزرو منقضی",summary.expired_reservations]].map(([k,v])=><div className="panel-card" key={k}><p className="text-sm text-primary/60">{k}</p><b className="text-3xl">{v??0}</b></div>)}</section><section className="panel-card flex justify-between"><div><h2 className="font-display text-2xl">موجودی و رهگیری</h2><p className="text-sm text-primary/60">available آزاد و reserved رزروشده است.</p></div><select className="rounded-full border px-4" value={location} onChange={e=>setLocation(e.target.value)}><option value="">همه مکان‌ها</option>{locations.map(x=><option key={x.id} value={x.id}>{x.name_fa}</option>)}</select></section><ErrorBox value={error}/><section className="grid gap-4 md:grid-cols-2 xl:grid-cols-3">{lots.map(x=><button key={x.id} onClick={()=>showTrace(x)} className="panel-card text-right"><div className="flex justify-between"><b>{x.lot_number}</b><Badge>{x.status}</Badge></div><p className="mt-2">{x.stone_name} • {x.location_name}</p><div className="mt-3 flex justify-between text-sm"><span>آزاد: {x.available_quantity}</span><span>رزرو: {x.reserved_quantity}</span><span>{x.quantity_unit}</span></div></button>)}</section>{selected&&<section className="panel-card"><h3 className="font-semibold">Traceability — {selected.lot_number}</h3>{trace.map((x,i)=><pre key={i} className="mt-2 overflow-auto rounded-xl bg-primary/5 p-3 text-xs" dir="ltr">{JSON.stringify(x,null,2)}</pre>)}</section>}</div>;
}

export function Shipments(){
 const [items,setItems]=useState([]),[status,setStatus]=useState(""),[error,setError]=useState("");useEffect(()=>{fetchJSON(`/api/v1/shipments${status?`?status=${status}`:""}`).then(r=>setItems(r.data||[])).catch(e=>setError(e.message))},[status]);return <div className="space-y-5" dir="rtl"><section className="panel-card flex justify-between"><div><h2 className="font-display text-2xl">محموله‌ها</h2><p className="text-sm text-primary/60">بارگیری، اعزام، رسیدن و تحویل جزئی</p></div><select value={status} onChange={e=>setStatus(e.target.value)} className="rounded-full border px-4"><option value="">همه</option>{Object.keys(fa).map(x=><option key={x}>{x}</option>)}</select></section><ErrorBox value={error}/><section className="grid gap-4 md:grid-cols-2">{items.map(x=><Link to={`/dashboard/shipments/${x.id}`} key={x.id} className="panel-card"><div className="flex justify-between"><b>{x.shipment_number}</b><Badge>{x.status}</Badge></div><p className="mt-2">سفارش {x.order_number} • {x.shipment_type}</p><small>{x.estimated_arrival_at?new Date(x.estimated_arrival_at).toLocaleString('fa-IR'):"ETA تعیین نشده"}</small></Link>)}</section></div>;
}

export function ShipmentDetail(){
 const {id}=useParams(),{hasPermission}=useAuth();const [shipment,setShipment]=useState(null),[error,setError]=useState(""),[busy,setBusy]=useState(false);const load=()=>fetchJSON(`/api/v1/shipments/${id}`).then(r=>setShipment(r.data)).catch(e=>setError(e.message));useEffect(()=>{load()},[id]);
 const operate=async action=>{const reason=prompt("توضیح عملیات:")||"ثبت عملیات";setBusy(true);try{await fetchJSON(`/api/v1/shipments/${id}/${action}`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({items:shipment.items.map(x=>({shipment_item_id:x.id,quantity:action==='deliver'?String(Number(x.loaded_quantity)-Number(x.delivered_quantity)):String(Number(x.planned_quantity)-Number(x.loaded_quantity))})),finalize_loading:action==='load',finalize_delivery:action==='deliver',reason,receiver_name:action==='deliver'?prompt("نام گیرنده:")||"گیرنده":""})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
 if(!shipment)return <div className="panel-card">{error||"در حال بارگذاری…"}</div>;const actions=[['load','shipments.load','بارگیری'],['dispatch','shipments.dispatch','اعزام'],['arrive','shipments.confirm_arrival','ثبت رسیدن'],['deliver','shipments.confirm_delivery','تحویل']];return <div className="space-y-5" dir="rtl"><section className="panel-card"><Link to="/dashboard/shipments" className="text-sm underline">بازگشت</Link><div className="mt-3 flex justify-between"><div><h2 className="font-display text-2xl">{shipment.shipment_number}</h2><p>سفارش {shipment.order_number} • {shipment.shipment_type}</p></div><Badge>{shipment.status}</Badge></div><div className="mt-5 flex flex-wrap gap-2">{actions.filter(x=>hasPermission(x[1])).map(x=><button disabled={busy} key={x[0]} onClick={()=>operate(x[0])} className="rounded-full bg-primary px-5 py-2 text-sand disabled:opacity-40">{x[2]}</button>)}{shipment.workflow_instance_id&&<Link to={`/dashboard/workflows/${shipment.workflow_instance_id}`} className="rounded-full border px-5 py-2">Workflow حمل</Link>}</div></section><section className="panel-card"><h3 className="font-semibold">اقلام محموله</h3>{shipment.items?.map(x=><div key={x.id} className="mt-3 grid gap-2 rounded-xl border p-3 sm:grid-cols-4"><b>{x.batch_number}</b><span>برنامه {x.planned_quantity}</span><span>بارگیری {x.loaded_quantity}</span><span>تحویل {x.delivered_quantity} {x.quantity_unit}</span></div>)}</section><ErrorBox value={error}/></div>;
}
