import { useEffect, useState } from "react";
import { Link } from "react-router-dom";
import { fetchJSON, idempotentHeaders } from "../lib/api";
import { PersianDate } from "../components/OperationalUI";
import { useAuth } from "../lib/auth";

export default function Notifications() {
  const{hasPermission}=useAuth();
  const [data,setData]=useState({items:[],unread_count:0}),[templates,setTemplates]=useState([]),[deliveries,setDeliveries]=useState([]),[error,setError]=useState("");
  const load=async()=>{try{const tasks=[fetchJSON("/api/v1/notifications?limit=100").then(r=>setData(r.data))];if(hasPermission("notifications.templates.manage"))tasks.push(fetchJSON("/api/v1/admin/notification-templates").then(r=>setTemplates(r.data||[])));if(["notifications.delivery.view","notifications.deliveries.retry","notifications.retry"].some(hasPermission))tasks.push(fetchJSON("/api/v1/admin/notification-deliveries?limit=100").then(r=>setDeliveries(r.data||[])));await Promise.all(tasks)}catch(e){setError(e.message)}};
  useEffect(()=>{load()},[]);
  const read=async item=>{if(item.status==="UNREAD")await fetchJSON(`/api/v1/notifications/${item.id}/read`,{method:"POST"});if(item.deep_link)window.location.assign(`/panel${item.deep_link.replace(/^\/panel/,"")}`);else load()};
  const saveTemplate=async item=>{try{await fetchJSON(`/api/v1/admin/notification-templates/${item.id}`,{method:"PUT",headers:idempotentHeaders(),body:JSON.stringify({title_template:item.title_template,body_template:item.body_template,is_active:item.is_active})});load()}catch(e){setError(e.message)}};
  return <div className="space-y-5" dir="rtl"><section className="panel-card flex items-center justify-between"><div><h2 className="font-display text-2xl">اعلان‌ها</h2><p className="text-sm text-primary/60">{data.unread_count} اعلان خوانده‌نشده</p></div><button onClick={async()=>{await fetchJSON("/api/v1/notifications/read-all",{method:"POST"});load()}} className="rounded-full border px-4 py-2">خواندن همه</button></section>{error&&<p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<section className="panel-card space-y-3">{data.items.map(item=><button key={item.id} onClick={()=>read(item)} className={`block w-full rounded-2xl border p-4 text-right ${item.status==="UNREAD"?"border-primary bg-primary/5":"opacity-70"}`}><span className="text-xs text-primary/50"><PersianDate value={item.created_at}/></span><b className="mt-1 block">{item.title}</b><p className="text-sm">{item.body}</p></button>)}{data.items.length===0&&<p>اعلانی وجود ندارد.</p>}</section>{hasPermission("notifications.templates.manage")&&<section className="panel-card space-y-3"><h3 className="font-semibold">قالب‌های امن اعلان</h3>{templates.map((item,index)=><div key={item.id} className="grid gap-2 rounded-xl border p-3 md:grid-cols-6"><span className="text-xs">{item.event_type}<br/>{item.channel}</span><input className="rounded-lg border p-2 md:col-span-2" value={item.title_template} onChange={e=>setTemplates(templates.map((x,i)=>i===index?{...x,title_template:e.target.value}:x))}/><textarea className="rounded-lg border p-2 md:col-span-2" value={item.body_template} onChange={e=>setTemplates(templates.map((x,i)=>i===index?{...x,body_template:e.target.value}:x))}/><button onClick={()=>saveTemplate(item)} className="rounded-lg border">ذخیره</button></div>)}</section>}{deliveries.length>0&&<section className="panel-card overflow-auto"><h3 className="mb-3 font-semibold">تحویل SMS و Outbox</h3><table className="w-full text-sm"><thead><tr><th>وضعیت</th><th>تلاش</th><th>خطا</th><th></th></tr></thead><tbody>{deliveries.map(x=><tr key={x.id} className="border-t"><td>{x.status}</td><td>{x.attempt_count}</td><td>{x.last_error}</td><td>{["FAILED","CANCELLED"].includes(x.status)&&["notifications.deliveries.retry","notifications.retry"].some(hasPermission)&&<button onClick={async()=>{await fetchJSON(`/api/v1/admin/notification-deliveries/${x.id}/retry`,{method:"POST",headers:idempotentHeaders(),body:"{}"});load()}} className="rounded-full border px-3 py-1">تلاش مجدد</button>}</td></tr>)}</tbody></table></section>}<Link to="/dashboard" className="underline">بازگشت به داشبورد</Link></div>;
}
