import { useEffect, useState } from "react";
import { fetchJSON } from "../lib/api";
import { useAuth } from "../lib/auth";

const reports=[{key:"overview",permission:"reports.overview.view",title:"نمای کلی"},{key:"receivables",permission:"reports.receivables.view",title:"مطالبات"},{key:"costs",permission:"reports.costs.view",title:"هزینه‌ها"},{key:"profitability",permission:"reports.profitability.view",title:"سودآوری"},{key:"operations",permission:"reports.operations.view",title:"عملیات"},{key:"sales",permission:"reports.sales.view",title:"پیگیری فروش"}];
export default function Reports(){const{hasPermission}=useAuth();const available=reports.filter(x=>hasPermission(x.permission));const[tab,setTab]=useState(available[0]?.key||"overview"),[data,setData]=useState(null),[error,setError]=useState("");useEffect(()=>{if(!tab)return;setData(null);setError("");fetchJSON(`/api/v1/admin/reports/${tab}`).then(r=>setData(r.data)).catch(e=>setError(e.message))},[tab]);return <div className="space-y-5" dir="rtl"><section className="panel-card"><h2 className="font-display text-2xl">گزارش‌های عملیاتی و مالی</h2><div className="mt-4 flex flex-wrap gap-2">{available.map(x=><button key={x.key} onClick={()=>setTab(x.key)} className={`rounded-full px-4 py-2 ${tab===x.key?"bg-primary text-sand":"border"}`}>{x.title}</button>)}</div></section>{error&&<p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}<section className="panel-card overflow-auto">{!data?<p>در حال بارگذاری…</p>:<ReportView data={data}/>}</section></div>}

function ReportView({data}){if(Array.isArray(data))return <ReportTable rows={data}/>;const entries=Object.entries(data||{}),metrics=entries.filter(([,v])=>!Array.isArray(v)&&typeof v!=="object"),groups=entries.filter(([,v])=>Array.isArray(v));return <div className="space-y-6"><div className="grid gap-3 md:grid-cols-3">{metrics.map(([key,value])=><div key={key} className="rounded-2xl bg-primary/5 p-4"><span className="text-xs text-primary/60">{label(key)}</span><b className="mt-1 block text-lg" dir="auto">{String(value??"—")}</b></div>)}</div>{groups.map(([key,rows])=><div key={key}><h3 className="mb-3 font-semibold">{label(key)}</h3><ReportTable rows={rows}/></div>)}</div>}
function ReportTable({rows}){if(!rows?.length)return <p className="text-sm text-primary/60">داده‌ای برای این بازه وجود ندارد.</p>;const columns=[...new Set(rows.flatMap(row=>Object.keys(row||{})))];return <table className="w-full min-w-[720px] text-sm"><thead><tr>{columns.map(c=><th key={c} className="border-b p-2 text-right">{label(c)}</th>)}</tr></thead><tbody>{rows.map((row,index)=><tr key={row.id||row.order_id||index} className="border-b border-primary/10">{columns.map(c=><td key={c} className="p-2" dir="auto">{typeof row[c]==="object"?JSON.stringify(row[c]):String(row[c]??"—")}</td>)}</tr>)}</tbody></table>}
function label(key){return ({active_orders:"سفارش فعال",overdue_receivables:"مطالبات عقب‌افتاده",pending_payments:"پرداخت در انتظار",pending_cost_approvals:"هزینه در انتظار تأیید",open_workflows:"Workflow باز",unissued_documents:"اسناد صادرنشده",by_currency:"تفکیک ارز",items:"ردیف‌ها",buckets:"بازه‌های مطالبات",revenue:"درآمد",approved_cost:"هزینه تأییدشده",estimated_cost:"هزینه تخمینی",reported_cost:"هزینه گزارش‌شده",profit:"سود تخمینی",margin_percentage:"حاشیه سود٪",outstanding_amount:"مانده مشتری",average_step_duration_hours:"میانگین زمان مرحله (ساعت)",rework_iterations:"تکرار اصلاحی",on_time_deliveries:"تحویل به‌موقع"}[key]||key.replaceAll("_"," "))}
