import { useEffect, useMemo, useState } from "react";
import { useNavigate, useParams } from "react-router-dom";
import { fetchJSON } from "../lib/api";

export default function RoleEditor() {
  const { id } = useParams(); const navigate = useNavigate();
  const [role,setRole]=useState(null),[permissions,setPermissions]=useState([]),[selected,setSelected]=useState([]),[search,setSearch]=useState(""),[message,setMessage]=useState("");
  useEffect(()=>{Promise.all([fetchJSON(`/api/v1/admin/roles/${id}`),fetchJSON("/api/v1/admin/permissions")]).then(([r,p])=>{setRole(r.data);setSelected(r.data.permission_codes||[]);setPermissions(p.data||[])})},[id]);
  const groups=useMemo(()=>permissions.filter(p=>`${p.name_fa} ${p.description_fa} ${p.code}`.toLowerCase().includes(search.toLowerCase())).reduce((a,p)=>{(a[p.group_code]||=[]).push(p);return a},{}),[permissions,search]);
  const toggle=(code)=>setSelected(v=>v.includes(code)?v.filter(x=>x!==code):[...v,code]);
  const save=async()=>{await fetchJSON(`/api/v1/admin/roles/${id}`,{method:"PATCH",body:JSON.stringify({name_fa:role.name_fa,description_fa:role.description_fa,is_active:role.is_active})});if(!role.is_protected)await fetchJSON(`/api/v1/admin/roles/${id}/permissions`,{method:"PUT",body:JSON.stringify({permission_codes:selected})});setMessage("نقش و دسترسی‌ها ذخیره شد.")};
  if(!role)return <p>در حال بارگذاری…</p>;
  return <div className="space-y-5" dir="rtl"><section className="panel-card"><button onClick={()=>navigate(-1)} className="text-sm">← بازگشت</button><div className="mt-3 grid gap-3 md:grid-cols-2"><input className="rounded-xl border p-3 text-lg font-semibold" value={role.name_fa} onChange={e=>setRole({...role,name_fa:e.target.value})}/><input className="rounded-xl border p-3" value={role.description_fa} onChange={e=>setRole({...role,description_fa:e.target.value})}/></div><label className="mt-3 block text-sm"><input className="ml-2" disabled={role.is_protected} type="checkbox" checked={role.is_active} onChange={e=>setRole({...role,is_active:e.target.checked})}/>نقش فعال است</label><p className="mt-2 text-sm text-primary/60">{selected.length} دسترسی انتخاب شده {role.is_protected&&"• نگاشت دسترسی این نقش محافظت‌شده است"}</p><input className="mt-4 w-full rounded-xl border p-3" placeholder="جست‌وجوی دسترسی" value={search} onChange={e=>setSearch(e.target.value)}/></section>
  {Object.entries(groups).map(([group,items])=><section className="panel-card" key={group}><div className="flex justify-between"><h3 className="font-semibold">{group}</h3><div className="space-x-2 space-x-reverse text-xs"><button disabled={role.is_protected} onClick={()=>setSelected([...new Set([...selected,...items.map(p=>p.code)])])}>انتخاب همه</button><button disabled={role.is_protected} onClick={()=>setSelected(selected.filter(c=>!items.some(p=>p.code===c)))}>پاک کردن</button></div></div><div className="mt-4 grid gap-2 md:grid-cols-2">{items.map(p=><label key={p.code} className="rounded-xl border p-3"><input disabled={role.is_protected} type="checkbox" className="ml-2" checked={selected.includes(p.code)} onChange={()=>toggle(p.code)}/><b className="text-sm">{p.name_fa}</b><code className="block text-[10px] text-primary/50" dir="ltr">{p.code}</code><small>{p.description_fa}</small></label>)}</div></section>)}
  <div className="sticky bottom-3 flex items-center gap-3 rounded-2xl bg-white p-3 shadow"><button onClick={save} className="rounded-full bg-primary px-6 py-3 text-sand">ذخیره کامل نقش</button>{message&&<span className="text-sm">{message}</span>}</div></div>;
}
