import { useEffect, useMemo, useState } from "react";
import { useParams } from "react-router-dom";
import DynamicFieldRenderer from "../components/DynamicFieldRenderer";
import { API_BASE, fetchJSON } from "../lib/api";
import { useAuth } from "../lib/auth";

const terminal = new Set(["COMPLETED", "SKIPPED", "CANCELLED"]);
const statusFA = { NOT_STARTED:"شروع‌نشده", WAITING_FOR_ASSIGNEE:"در انتظار مسئول", IN_PROGRESS:"در حال انجام", WAITING_FOR_APPROVAL:"در انتظار تأیید", WAITING_FOR_TRANSITION:"در انتظار انتخاب مسیر", NEEDS_CORRECTION:"نیازمند اصلاح", HAS_MISMATCH:"دارای مغایرت", COMPLETED:"تکمیل‌شده", SKIPPED:"عبور‌شده" };

function ProformaPanel({ orderId, onIssued }) {
  const [form,setForm]=useState({currency:"IRR",subtotal:"0",discount_amount:"0",notes:""});
  const [created,setCreated]=useState(null);
  const create=async event=>{event.preventDefault();const response=await fetchJSON(`/api/v1/orders/${orderId}/proformas`,{method:"POST",body:JSON.stringify(form)});setCreated(response.data)};
  const issue=async()=>{await fetchJSON(`/api/v1/proformas/${created.id}/issue`,{method:"POST"});onIssued()};
  return <form onSubmit={create} className="mt-5 grid gap-3 rounded-2xl border bg-primary/5 p-4 md:grid-cols-2"><h4 className="md:col-span-2 font-semibold">صدور پیش‌فاکتور</h4><select className="rounded-xl border p-3" value={form.currency} onChange={e=>setForm({...form,currency:e.target.value})}><option>IRR</option><option>USD</option><option>EUR</option></select><input className="rounded-xl border p-3" type="number" min="0" value={form.subtotal} onChange={e=>setForm({...form,subtotal:e.target.value})}/><input className="rounded-xl border p-3" type="number" min="0" value={form.discount_amount} onChange={e=>setForm({...form,discount_amount:e.target.value})}/><textarea className="rounded-xl border p-3" placeholder="توضیحات" value={form.notes} onChange={e=>setForm({...form,notes:e.target.value})}/>{!created?<button className="rounded-full bg-primary px-5 py-2 text-sand">ساخت پیش‌نویس</button>:<button type="button" onClick={issue} className="rounded-full bg-green-700 px-5 py-2 text-white">صدور و تکمیل مرحله</button>}</form>;
}

export default function WorkflowRuntime(){
  const { workflowInstanceId }=useParams();
  const { hasPermission }=useAuth();
  const [workflow,setWorkflow]=useState(null),[selectedID,setSelectedID]=useState(null),[values,setValues]=useState({}),[transitions,setTransitions]=useState([]),[error,setError]=useState(""),[busy,setBusy]=useState(false);
  const load=async()=>{try{const response=await fetchJSON(`/api/v1/workflow-instances/${workflowInstanceId}/runtime`);const data=response.data;setWorkflow(data);setSelectedID(current=>current||data.current_step_instance_id||data.steps?.[0]?.id)}catch(e){setError(e.message)}};
  useEffect(()=>{load()},[workflowInstanceId]);
  const step=useMemo(()=>workflow?.steps?.find(item=>item.id===selectedID),[workflow,selectedID]);
  useEffect(()=>{if(step){const initial={};step.fields?.forEach(field=>{if(field.value!==undefined&&field.value!==null)initial[field.field_key]=field.value;else if(field.default_value!==undefined&&field.default_value!==null)initial[field.field_key]=field.default_value});setValues(initial)}},[step?.id]);
  useEffect(()=>{if(!step||!hasPermission("workflow_transitions.view")){setTransitions([]);return}fetchJSON(`/api/v1/workflow-step-instances/${step.id}/transitions`).then(r=>setTransitions(r.data||[])).catch(()=>setTransitions([]))},[step?.id]);
  const call=async(action,body={})=>{setBusy(true);setError("");try{await fetchJSON(`/api/v1/workflow-step-instances/${step.id}/${action}`,{method:action==="draft"?"PUT":"POST",body:JSON.stringify(body)});await load()}catch(e){setError(e.message)}finally{setBusy(false)}};
  const reason=label=>window.prompt(`دلیل ${label} را وارد کنید:`)||"";
  const upload=async(field,file)=>{const data=new FormData();data.append("field_definition_id",field.id);data.append("file",file);const response=await fetch(`${API_BASE}/api/v1/workflow-step-instances/${step.id}/files`,{method:"POST",credentials:"include",body:data});if(!response.ok)throw new Error("بارگذاری فایل انجام نشد");const payload=await response.json();setValues(current=>({...current,[field.field_key]:{fileId:payload.data.id}}))};
  if(!workflow)return <div className="panel-card" dir="rtl">{error||"در حال بارگذاری…"}</div>;
  return <div className="space-y-5" dir="rtl">
    <section className="panel-card"><div className="flex flex-wrap justify-between gap-4"><div><p className="text-xs text-primary/55">{workflow.workflow_name} • نسخه {workflow.template_version_number} • Scope: {workflow.scope_type}</p><h2 className="font-display text-2xl">سفارش {workflow.order_number}</h2><p className="mt-1 text-sm">مشتری: {workflow.customer_name}</p></div><span className="h-fit rounded-full bg-primary/10 px-4 py-2 text-sm">{statusFA[workflow.status]||workflow.status}</span></div></section>
    <div className="grid gap-5 lg:grid-cols-[280px,1fr]"><aside className="panel-card h-fit"><h3 className="font-semibold">Timeline فرایند</h3><ol className="mt-4 space-y-2">{workflow.steps.map(item=><li key={item.id}><button onClick={()=>setSelectedID(item.id)} className={`w-full rounded-xl border p-3 text-right ${item.id===step?.id?"border-primary bg-primary text-sand":"bg-white"}`}><span className="block text-xs opacity-70">{item.sequence_number}. {statusFA[item.status]||item.status}</span><b>{item.internal_title_fa||item.customer_title_fa}</b>{item.is_overdue&&<span className="mt-1 block text-xs text-red-500">{item.delay_hours} ساعت تأخیر</span>}</button></li>)}</ol></aside>
      <main className="space-y-5">{step&&<section className="panel-card"><div className="flex flex-wrap justify-between gap-3"><div><h3 className="text-xl font-semibold">{step.internal_title_fa}</h3><p className="text-sm text-primary/60">{step.internal_description_fa}</p></div><span className="rounded-full bg-amber-50 px-3 py-1 text-sm">{statusFA[step.status]||step.status}</span></div>
        {step.fields?.length>0&&<div className="mt-6 grid gap-5 md:grid-cols-2">{step.fields.map(field=><DynamicFieldRenderer key={field.id} field={field} value={values[field.field_key]} disabled={terminal.has(step.status)||step.status==="WAITING_FOR_APPROVAL"} onChange={value=>setValues(current=>({...current,[field.field_key]:value}))} onUpload={file=>upload(field,file)}/>)}</div>}
        {step.step_code==="ISSUE_PROFORMA"&&!terminal.has(step.status)&&<ProformaPanel orderId={workflow.order_id} onIssued={load}/>} 
        {step.step_code!=="ISSUE_PROFORMA"&&<div className="mt-6 flex flex-wrap gap-2">{["WAITING_FOR_ASSIGNEE","NEEDS_CORRECTION"].includes(step.status)&&<button disabled={busy} onClick={()=>call("start",{})} className="rounded-full bg-primary px-5 py-2 text-sand">شروع مرحله</button>}{step.status==="IN_PROGRESS"&&<><button disabled={busy} onClick={()=>call("draft",{values})} className="rounded-full border px-5 py-2">ذخیره پیش‌نویس</button><button disabled={busy} onClick={()=>call("submit",{values})} className="rounded-full bg-green-700 px-5 py-2 text-white">ثبت مرحله</button></>}{step.status==="WAITING_FOR_APPROVAL"&&hasPermission("workflow_steps.approve")&&<><button disabled={busy} onClick={()=>call("approve",{reason:""})} className="rounded-full bg-green-700 px-5 py-2 text-white">تأیید</button><button disabled={busy} onClick={()=>{const value=reason("رد");if(value)call("reject",{reason:value})}} className="rounded-full bg-red-700 px-5 py-2 text-white">رد برای اصلاح</button></>}{step.status==="WAITING_FOR_TRANSITION"&&hasPermission("workflow_transitions.select")&&transitions.map(x=><button key={x.id} disabled={busy} onClick={async()=>{const why=x.requires_reason?reason("انتخاب مسیر"):"";if(x.requires_reason&&!why)return;setBusy(true);try{await fetchJSON(`/api/v1/workflow-step-instances/${step.id}/select-transition`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({transition_code:x.transition_code,reason:why})});await load()}catch(e){setError(e.message)}finally{setBusy(false)}}} className="rounded-full bg-blue-700 px-5 py-2 text-white">{x.label_fa}</button>)}{step.is_skippable&&!terminal.has(step.status)&&step.status!=="WAITING_FOR_TRANSITION"&&<button disabled={busy} onClick={()=>{const value=reason("عبور");if(value)call("skip",{reason:value})}} className="rounded-full border px-5 py-2">عبور از مرحله</button>}{terminal.has(step.status)&&hasPermission("workflow_steps.reopen")&&<button disabled={busy} onClick={()=>{const value=reason("بازگشایی");if(value)call("reopen",{reason:value})}} className="rounded-full border px-5 py-2">بازگشایی</button>}{hasPermission("workflow_steps.reassign")&&!terminal.has(step.status)&&<button disabled={busy} onClick={()=>{const user=window.prompt("شناسه کاربر جدید:");const why=reason("تخصیص مجدد");if(user&&why)call("reassign",{assigned_user_id:user,reason:why})}} className="rounded-full border px-5 py-2">تخصیص مجدد</button>}</div>}
      </section>}
      {workflow.discrepancies?.length>0&&<section className="panel-card"><h3 className="font-semibold">مغایرت‌ها</h3><div className="mt-3 space-y-2">{workflow.discrepancies.map(item=><div key={item.id} className="rounded-xl border p-3"><b>{item.metric_key}</b> — انتظار {item.expected_value} / ثبت {item.actual_value}<span className={`mr-3 rounded-full px-2 py-1 text-xs ${item.is_blocking?"bg-red-100":"bg-amber-100"}`}>{item.severity}</span>{hasPermission("workflow_discrepancies.resolve")&&!terminal.has(item.status)&&<button onClick={async()=>{const note=reason("رفع مغایرت");if(note){await fetchJSON(`/api/v1/workflow-discrepancies/${item.id}/resolve`,{method:"POST",body:JSON.stringify({status:"RESOLVED",note})});load()}}} className="mr-3 underline">رفع شد</button>}</div>)}</div></section>}
      {workflow.action_items?.length>0&&<section className="panel-card"><h3 className="font-semibold">اقدام‌های باز</h3>{workflow.action_items.map(item=><div key={item.id} className="mt-3 flex items-center justify-between rounded-xl border p-3"><span>{item.title_fa}{item.is_blocking&&<b className="mr-2 text-red-700">مسدودکننده</b>}</span>{hasPermission("action_items.complete")&&<button onClick={async()=>{await fetchJSON(`/api/v1/action-items/${item.id}/complete`,{method:"POST"});load()}} className="rounded-full border px-3 py-1 text-xs">تکمیل</button>}</div>)}</section>}
      {workflow.proformas?.length>0&&<section className="panel-card"><h3 className="font-semibold">پیش‌فاکتورها و اطلاعات مالی مجاز</h3>{workflow.proformas.map(item=><div key={item.id} className="mt-3 grid grid-cols-2 gap-2 rounded-xl border p-3 text-sm"><b>{item.proforma_number}</b><span>{item.status}</span><span>جمع: {item.subtotal} {item.currency}</span><span>تخفیف: {item.discount_amount} {item.currency}</span><strong>مبلغ نهایی: {item.total_amount} {item.currency}</strong></div>)}</section>}
      {workflow.audit_summary?.length>0&&<section className="panel-card"><h3 className="font-semibold">خلاصه Audit</h3>{workflow.audit_summary.map((item,index)=><div key={`${item.created_at}-${index}`} className="mt-2 flex flex-wrap justify-between rounded-xl border p-3 text-xs"><span>{item.actor} • {item.action_code}</span><time>{new Date(item.created_at).toLocaleString("fa-IR")}</time></div>)}</section>}
      </main></div>{error&&<p className="rounded-xl bg-red-50 p-4 text-red-700">{error}</p>}
  </div>
}
