import { useEffect, useState } from "react";
import { fetchJSON } from "../lib/api";

const money=(value,currency)=>`${new Intl.NumberFormat("fa-IR").format(Number(value||0))} ${currency}`;
const statusFA={NOT_STARTED:"در انتظار شروع",WAITING_FOR_ASSIGNEE:"در انتظار شروع",IN_PROGRESS:"در حال انجام",WAITING_FOR_APPROVAL:"در حال بررسی",NEEDS_CORRECTION:"در حال تکمیل",HAS_MISMATCH:"در حال تکمیل",COMPLETED:"تکمیل شده",CANCELLED:"لغو شده"};
const showValue=value=>{
  if(value===undefined||value===null)return "—";
  if(typeof value==="boolean")return value?"بله":"خیر";
  if(typeof value==="object"&&!Array.isArray(value))return value.amount!==undefined?`${value.amount} ${value.currency||""}`:value.value!==undefined?`${value.value} ${value.unit||""}`:"";
  return Array.isArray(value)?value.join("، "):String(value);
};

function OrderRuntime({id}){
  const [runtime,setRuntime]=useState(null),[progress,setProgress]=useState(null),[shipments,setShipments]=useState([]),[error,setError]=useState("");
  const load=()=>fetchJSON(`/api/v1/workflow-instances/${id}/runtime`).then(async response=>{setRuntime(response.data);const orderID=response.data.order_id;const [p,s]=await Promise.all([fetchJSON(`/api/v1/account/orders/${orderID}/progress`),fetchJSON(`/api/v1/account/orders/${orderID}/shipments`)]);setProgress(p.data);setShipments(s.data||[])}).catch(e=>setError(e.message));
  useEffect(()=>{load()},[id]);
  if(error)return <p className="mt-4 text-sm text-red-700">نمایش جزئیات ممکن نیست.</p>;
  if(!runtime)return <p className="mt-4 text-sm">در حال دریافت جزئیات…</p>;
  const confirm=async shipment=>{const receiver=prompt("نام تحویل‌گیرنده:");if(!receiver)return;await fetchJSON(`/api/v1/account/orders/${runtime.order_id}/shipments/${shipment.id}/confirm-delivery`,{method:"POST",headers:{"Idempotency-Key":crypto.randomUUID()},body:JSON.stringify({receiver_name:receiver,reason:"تأیید مشتری"})});load()};
  return <div className="mt-5 space-y-5">{progress&&<section className="rounded-2xl bg-primary/5 p-4"><div className="flex justify-between"><b>پیشرفت کل سفارش</b><strong>{progress.overall_progress}%</strong></div><div className="mt-2 h-2 overflow-hidden rounded-full bg-white"><div className="h-full bg-primary" style={{width:`${progress.overall_progress}%`}}/></div>{progress.items.map(item=><div key={item.order_item_id} className="mt-4 rounded-xl bg-white/70 p-3"><div className="flex justify-between"><b>{item.stone_name}</b><span>{item.overall_progress}%</span></div><p className="mt-1 text-xs text-primary/60">آماده {item.packaged.quantity} • ارسال {item.shipped.quantity} • تحویل {item.delivered.quantity} از {item.ordered_quantity} {item.quantity_unit}</p></div>)}</section>}<ol className="border-r-2 border-primary/15 pr-5">{runtime.steps.map(step=><li key={step.id} className="relative mb-5"><span className="absolute -right-[1.65rem] top-1 h-3 w-3 rounded-full bg-primary"/><b>{step.customer_title_fa}</b><span className="mr-2 rounded-full bg-primary/5 px-2 py-1 text-xs">{statusFA[step.status]||step.customer_status}</span>{step.customer_description_fa&&<p className="text-sm text-primary/60">{step.customer_description_fa}</p>}{step.fields?.length>0&&<dl className="mt-2 grid gap-2 rounded-xl bg-white/60 p-3 sm:grid-cols-2">{step.fields.map(field=><div key={field.id}><dt className="text-xs text-primary/55">{field.label_fa}</dt><dd>{field.field_type==="FILE"||field.field_type==="IMAGE"||field.field_type==="SIGNATURE"?(field.value?.fileId?<a className="underline" href={`/api/v1/workflow-files/${field.value.fileId}`} target="_blank" rel="noreferrer">مشاهده فایل</a>:"—"):showValue(field.value)}</dd></div>)}</dl>}</li>)}</ol>{shipments.length>0&&<section><h3 className="font-semibold">محموله‌های سفارش</h3>{shipments.map(s=><article key={s.id} className="mt-3 rounded-xl border p-4"><div className="flex flex-wrap justify-between gap-2"><div><b>{s.customer_title_fa||`محموله ${s.shipment_number}`}</b><p className="text-xs text-primary/60">ETA: {s.estimated_arrival_at?new Date(s.estimated_arrival_at).toLocaleString('fa-IR'):"در حال تعیین"}</p></div><span>{statusFA[s.status]||s.status}</span></div>{["ARRIVED","PARTIALLY_DELIVERED"].includes(s.status)&&<button onClick={()=>confirm(s)} className="mt-3 rounded-full bg-primary px-4 py-2 text-sm text-sand">تأیید دریافت کامل</button>}</article>)}</section>}</div>;
}

export default function Account(){
  const [orders,setOrders]=useState([]),[proformas,setProformas]=useState([]),[tab,setTab]=useState("orders"),[expanded,setExpanded]=useState(null),[loading,setLoading]=useState(true),[error,setError]=useState("");
  useEffect(()=>{Promise.all([fetchJSON("/api/v1/account/orders"),fetchJSON("/api/v1/account/proformas")]).then(([o,p])=>{setOrders(o.data||[]);setProformas(p.data||[])}).catch(e=>setError(e.status===403?"این حساب هنوز برای مشاهده سفارش‌ها فعال نشده است.":e.message)).finally(()=>setLoading(false))},[]);
  return <section className="section-shell py-12" dir="rtl"><div className="mx-auto max-w-5xl"><h1 className="font-display text-4xl">حساب سفارش‌های من</h1><p className="mt-2 text-primary/65">وضعیت پیش‌فاکتورها و مسیر پیشرفت سفارش</p><div className="my-6 flex gap-2"><button onClick={()=>setTab("orders")} className={`rounded-full px-5 py-2 ${tab==="orders"?"bg-primary text-sand":"border"}`}>سفارش‌ها</button><button onClick={()=>setTab("proformas")} className={`rounded-full px-5 py-2 ${tab==="proformas"?"bg-primary text-sand":"border"}`}>پیش‌فاکتورها</button></div>{loading&&<p>در حال بارگذاری…</p>}{error&&<div className="rounded-xl bg-amber-50 p-4 text-amber-900">{error}</div>}{!loading&&!error&&tab==="orders"&&<div className="grid gap-5">{orders.length===0?<p className="glass-panel rounded-2xl p-5">هنوز سفارشی ثبت نشده است.</p>:orders.map(order=><article key={order.id} className="glass-panel rounded-3xl p-6"><div className="flex flex-wrap justify-between gap-3"><div><h2 className="text-xl font-semibold">{order.workflow_name}</h2><code dir="ltr">{order.order_number}</code></div><span className="rounded-full bg-primary/10 px-3 py-1 text-sm">{statusFA[order.status]||order.status}</span></div><p className="mt-3 text-xs text-primary/55">شروع: {new Date(order.created_at).toLocaleDateString("fa-IR")}</p><button onClick={()=>setExpanded(expanded===order.id?null:order.id)} className="mt-4 rounded-full border px-4 py-2 text-sm">{expanded===order.id?"بستن جزئیات":"مشاهده روند کامل"}</button>{expanded===order.id&&<OrderRuntime id={order.workflow_instance_id}/>}</article>)}</div>}{!loading&&!error&&tab==="proformas"&&<div className="grid gap-4 md:grid-cols-2">{proformas.length===0?<p>هنوز پیش‌فاکتوری صادر نشده است.</p>:proformas.map(p=><article key={p.id} className="glass-panel rounded-3xl p-6"><div className="flex justify-between"><h2 className="font-semibold">پیش‌فاکتور {p.proforma_number}</h2><span>{p.status}</span></div><p className="mt-4 text-2xl font-semibold">{money(p.total_amount,p.currency)}</p><p className="mt-2 text-sm text-primary/60">تاریخ صدور: {p.issued_at?new Date(p.issued_at).toLocaleDateString("fa-IR"):"—"}</p><button onClick={()=>window.print()} className="mt-4 rounded-full border px-4 py-2 text-sm">مشاهده / چاپ</button></article>)}</div>}</div></section>;
}
